# Generated by Django 4.2.6 on 2023-10-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("safescore", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CsvReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("csv_file", models.FileField(upload_to="csv_reports/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="CSVFile",
        ),
    ]
