# Generated by Django 4.2.6 on 2023-10-29 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("safescore", "0003_report_analytics"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Report",
        ),
    ]
