# Generated by Django 4.2.6 on 2023-11-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("safescore", "0004_delete_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="RtspLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name="video",
            old_name="video_file",
            new_name="file",
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
