# Generated by Django 4.2.6 on 2023-11-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("safescore", "0005_rtsplink_rename_video_file_video_file_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RtspLink",
        ),
        migrations.RenameField(
            model_name="video",
            old_name="file",
            new_name="video_file",
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
